### PR TITLE
Fixes #858: Add count param in ListSkillService.java

### LINKED ISSUE #858: Add option to accept count=x param to return Top x skills after filtering
**Actual Behaviour**
Feature not present

**Expected Behaviour**
* Add option to accept count=x param to return Top x skills after filtering

**Steps to reproduce it**
NA

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #858 

Changes: [Add here what changes were made in this issue and if possible provide links.]
* Add count param in ListSkillService.java
* Will be used in the home page of Skill CMS to suppose display Top 5 skills, etc

Screenshots for the change: 
NA

### CODE REVIEW

File: src/ai/susi/server/api/cms/ListSkillService.java [hunk 1]
```diff
@@ -48,6 +49,22 @@ public ServiceResponse serviceImpl(Query call, HttpServletResponse response, Aut
         JSONArray jsonArray = new JSONArray();
         JSONObject json = new JSONObject(true);
         JSONObject skillObject = new JSONObject();
+        String countString = call.get("count", null);
```
Comment (AnupKumarPanwar) [inline src/ai/susi/server/api/cms/ListSkillService.java]: You get get count here directly. call.get() returns the the data type as per the default value.

**Comment by AnupKumarPanwar** [comment]
The functioning looks good, but another approach can be to initialise count to the passed value or jsonArray.length based on whether to apply countFilter or not and update the loop parameters accordingly. Rest LGTM.
