### PR TITLE
Store private skills in different repository

### LINKED ISSUE #863: Store private skills of the users in another git repository
**Actual Behaviour**

Currently, the "private" skills made by the users is published in the public [susi_skill_data](https://github.com/fossasia/susi_skill_data) repository

**Expected Behaviour**

All private skills must be published in another git repository which will not be public. The skill data will have a different structure than the existing public repo and the skills will be co related to the ids of the users who created them. 
This is corresponding to [#738#issuecomment-398121894](https://github.com/fossasia/susi_server/issues/738#issuecomment-398121894).
This will be the first step to creating private skills. The next step will include applying the private skill only to the conversations of that particular user and not to whole of SUSI.

**Steps to reproduce it**

Make a skill in the botbuilder. It will be public.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes #863 

Changes: 
- In `CreateSkillService.java` detect if the client sends an attribute `private`. If it sends, then store the skill in the `susi_private_skill_data` repository. Else store in normally in the `susi_skill_data` repository.
- In `SusiSkill.java` check for empty folder, otherwise it was throwing an error.

Screenshots for the change: 
directory structure in the repository:
```
└── users
    ├── user1id
    │   ├──  custom
    │       ├── Alarms\ and\ Clocks
    ├── user2id
    │   ├──  custom
    │       ├── Alarms\ and\ Clocks
```
Eg: On executing it locally, the private skill was successfully stored in:
image

### CODE REVIEW

File: src/ai/susi/server/api/cms/CreatePrivateSkillService.java [hunk 1]
```diff
@@ -0,0 +1,209 @@
+package ai.susi.server.api.cms;
```
Comment (Orbiter) [inline src/ai/susi/server/api/cms/CreatePrivateSkillService.java]: up to here it's fine but I don't see a requirement to make a new servlet. The private skill shall also be made with the CreateSkillService.java servlet and that servlet needs to read a 'private' attribute and then act acordingly

Comment (hkedia321) [reply src/ai/susi/server/api/cms/CreatePrivateSkillService.java]: @Orbiter I have now removed the new API and made changes to the  `CreateSkillService.java` file to detect `private` attribute and then store them in `susi_private_skill_data` repository. Please review. Thanks,
