### PR TITLE
Fixes issue #575 Grammatical errors in response message 

### LINKED ISSUE #575: Grammatical errors in response message
**Actual Behaviour**
The response message is being used to display in chat.susi.ai and the grammatical error is being reflected in dialog boxes.
[https://github.com/fossasia/chat.susi.ai/issues/794](url)
image

**Expected Behaviour**

Display grammatically response messages (ex: Full stop at the end, First character to be uppercase, etc.)

**Steps to reproduce it**

Change the response images

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by tstreamDOTh**
Fixes #575 

Changes: 
Fixed grammatical errors in response images.

### CODE REVIEW

File: src/ai/susi/server/api/aaa/PasswordChangeService.java [hunk 1]
```diff
@@ -71,8 +71,8 @@ public ServiceResponse serviceImpl(Query post, HttpServletResponse response, Aut
             salt = authentication.getString("salt");
         } catch (Throwable e) {
             DAO.log("Invalid password try for user: " + identity.getName() + " from host: " + post.getClientHost() + " : password or salt missing in database");
-            result.put("message", "invalid credentials");
-            throw new APIException(422, "Invalid credentials");
+            result.put("message", "Invalid credentials. ");
+            throw new APIException(422, "Invalid credentials. ");
```
Comment (dynamitechetan) [inline src/ai/susi/server/api/aaa/PasswordChangeService.java]: remove "." from throw new APIException(422, "Invalid credentials. "); 
I think it is not required as it is an error message from the API. Users will only see the message object of the JSON response.

**Comment by tstreamDOTh** [comment]
@dynamitechetan I will make the changes and let you after squashing the commits.
