### PR TITLE
Fixes #1179: Update Error codes

### LINKED ISSUE #1179: Same error codes are being used for all API exceptions.
**Actual Behaviour**
Same Error Codes are used for all API Exceptions
```
       if (!skill.exists()) {
            throw new APIException(422, "Skill does not exist.");
        }

        if (user_bookmark == null) {
            throw new APIException(422, "Bookmark not provided.");
        }

        skill_bookmark = Integer.parseInt(user_bookmark);

        if(skill_bookmark != 0 && skill_bookmark != 1) {
            throw new APIException(422, "Invalid Bookmark provided.");
        }
```
The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate. 

**Expected Behaviour**
Each type of error must have a different error code

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by sakshee-19**
References issue #1179

Changes: Updated error codes and messages for existing error codes.

Screenshots for the change:

### CODE REVIEW

File: src/ai/susi/server/api/aaa/ChangeUserRoles.java [hunk 1]
```diff
@@ -149,15 +149,15 @@ public ServiceResponse serviceImpl(Query query, HttpServletResponse response, Au
...
-                throw new APIException(400, "Username not found");
+                throw new APIException(404, "Username not found");
             }
 
             // Update the local database
             Authorization auth = DAO.getAuthorization(identity);
             try {
                 auth.setUserRole(userRole);
             } catch (IllegalArgumentException e) {
-                throw new APIException(400, "role not found");
```
Comment (ms10398) [inline src/ai/susi/server/api/aaa/ChangeUserRoles.java]: @Orbiter just to be sure 

But the exception was thrown because the query string didn't had proper role argument so instead of a `404` it should be a `400` -> Bad Data

What do you suggest about it

File: src/ai/susi/server/api/aaa/LoginService.java [hunk 2]
```diff
@@ -298,9 +298,9 @@ else if(pubkeyLogin){ // second part of pubkey login: verify if the response to
 				sig.update(challenge.getBytes());
 				verified = sig.verify(Base64.getDecoder().decode(challangeResponse));
 			} catch (NoSuchAlgorithmException e){
-				throw new APIException(400, "No such algorithm");
```
Comment (ms10398) [inline src/ai/susi/server/api/aaa/LoginService.java]: I think here should also not be a 404 because the parameter are wrong but the route exist

File: src/ai/susi/server/api/aaa/ModifyUserDevices.java [hunk 3]
```diff
@@ -98,7 +98,7 @@ public ServiceResponse serviceImpl(Query call, HttpServletResponse response, Aut
                             }
                         }
                         else {
-                            throw new APIException(400, "Specified device does not exist.");
```
Comment (ms10398) [inline src/ai/susi/server/api/aaa/ModifyUserDevices.java]: I think it should also not be a 404

As the device name which was provided as query string is not present

So the error code should be `422` or `400`

File: src/ai/susi/server/api/aaa/DeleteGroupService.java [hunk 4]
```diff
@@ -81,7 +81,7 @@ public ServiceResponse serviceImpl(Query post, HttpServletResponse response, Aut
                 result.put("message", "Group deleted successfully");
                 return new ServiceResponse(result);
             } else {
-                throw new APIException(422, "Group doesn't exists");
+                throw new APIException(401, "Group doesn't exists");
```
Comment (ms10398) [inline src/ai/susi/server/api/aaa/DeleteGroupService.java]: 401 is used for `unauthorized` status

but here the group doesn't exist so shouldn't it be a `422` or `400`

File: src/ai/susi/server/api/aaa/ChangeUserRoles.java [hunk 5]
```diff
@@ -149,15 +149,15 @@ public ServiceResponse serviceImpl(Query query, HttpServletResponse response, Au
             ClientCredential credential = new ClientCredential(ClientCredential.Type.passwd_login, userTobeUpgraded);
             ClientIdentity identity = new ClientIdentity(ClientIdentity.Type.email, credential.getName());
             if (!DAO.hasAuthorization(identity)) {
-                throw new APIException(400, "Username not found");
+                throw new APIException(404, "Username not found");
```
Comment (ms10398) [inline src/ai/susi/server/api/aaa/ChangeUserRoles.java]: It shouldn't be a 404 as the route is present and a param of username provided is only wrong
