### PR TITLE
Fix key on no user level API #1369

### LINKED ISSUE #1369: Fix User Level API Key on no user key found
**Actual Behaviour**

Currently, endpoint https://api.susi.ai/aaa/getApiKeys.json?type=user&access_token= is giving an error

**Expected Behaviour**

Fix it

org.json.JSONException: JSONObject["user"] not found.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1369

Changes: Fix key on no user-level API

### CODE REVIEW

File: src/ai/susi/server/api/aaa/GetApiKeys.java [hunk 1]
```diff
@@ -93,8 +93,8 @@ public ServiceResponse serviceImpl(Query call, HttpServletResponse response, Aut
             if (authentication.getIdentity() != null) {
                 ClientIdentity identity = authentication.getIdentity();
                 String userId = identity.getUuid();
-                JSONObject userKeys = apiKeys.getJSONObject("user");
-                configKeys = userKeys.has(userId) ? userKeys.getJSONObject(userId) : null;
+                JSONObject userKeys = userId != null && apiKeys.has("user") ? apiKeys.getJSONObject("user") : null;
+                configKeys = userKeys != null && userKeys.has(userId) ? userKeys.getJSONObject(userId) : null;
```
Comment (akshatnitd) [inline src/ai/susi/server/api/aaa/GetApiKeys.java]: In case there is no entry for user, we need to create the entry. That case is not handled.

**Comment by fragm3** [comment]
@akshatnitd fixed it: 
```
{
  "keys": {},
  "session": {"identity": {
    "type": "email",
    "name": "ShubhamQWE23@gmail.com",
    "anonymous": false
  }},
  "accepted": true,
  "message": "Success : Fetched all API key successfully !"
}
```
