### PR TITLE
[do not merge] fixed null ptr exception; added sample request

### LINKED ISSUE #514: bug in resend verification link.
parameter name in request is 'emailid'
parameter extracted from the request is 'emailId'
this is a typo which leads to null pointer exception

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes #514 , #518 

Changes: extraction of parameter from link

### CODE REVIEW

**Comment by DravitLochan** [comment]
@Orbiter @mariobehling @saurabhjn76 @dynamitechetan Please review and merge

File: src/ai/susi/server/api/aaa/ResendVerificationLinkService.java [hunk 1]
```diff
@@ -31,6 +31,9 @@
 
 /**
  * Created by dravit on 25/7/17.
+ * parameter : emailId
+ * sample request : 
+ * http://127.0.0.1:4000/aaa/resendVerificatiionLink.json?emailId=example@example.com
```
Comment (mariobehling) [inline src/ai/susi/server/api/aaa/ResendVerificationLinkService.java]: example.com?

Comment (DravitLochan) [inline src/ai/susi/server/api/aaa/ResendVerificationLinkService.java]: I thought we just need to show examples hence used it as dummy data. I have updated it to a proper one now. Thanks for pointing out. There was another typo 'in resendVerificatiionLink'. fixed that as well.
